# Schema for the configuration files of the acquia_product_tokens module.

acquia_product_tokens.settings:
  type: config_object
  label: 'Acquia Product Token settings'
  mapping:
    tokens:
      type: text
      label: 'Definition of Acquia Products and tokens'
    missing_token_text:
      type: string
      label: 'Replacement text for missing Acquia Product tokens'
